// src/utils/measurementCNN.js
// ─────────────────────────────────────────────────────────────────────────────
// TensorFlow.js model loader and inference wrapper for the 13-class
// measurement character CNN.
//
// Model source priority
// ─────────────────────
//  1. /models/measurement-recognizer/model.json  (generated by Python training
//     script — best accuracy, < 500 KB)
//  2. Built-in untrained fallback (geometry-only detection still works; CNN
//     predictions will be low-confidence and deferred to geometry detector)
//
// The model runs 100 % locally in the browser — no network calls after the
// initial page load that caches the weights in the browser's HTTP cache.
//
// Input format
// ────────────
//  Any HTMLCanvasElement.  The module normalises it to 28×28 greyscale,
//  inverts so ink=1/background=0 (MNIST convention), and feeds [1,28,28,1].
//
// Output format
// ─────────────
//  { char: string, confidence: number, all: Float32Array }
//  char       – one of: '0'-'9'  |  "'"  |  '"'  |  '-'
//  confidence – softmax probability of the top class  (0.0–1.0)
//  all        – full 13-element softmax array  (index matches CLASSES)
// ─────────────────────────────────────────────────────────────────────────────

export const CLASSES     = ['0','1','2','3','4','5','6','7','8','9',"'",'"','-'];
export const IMG_SIZE    = 28;      // must match training script
const MODEL_URL          = '/models/measurement-recognizer/model.json';
const CLASSES_URL        = '/models/measurement-recognizer/classes.json';
const WARMUP_RUNS        = 2;       // dummy predictions to JIT-compile the model

export default class MeasurementCNN {
  constructor() {
    this._model    = null;
    this._classes  = [...CLASSES];
    this._loading  = null;
    this._loaded   = false;
  }

  get isLoaded() { return this._loaded; }
  get classes()  { return this._classes; }

  // ── Loading ────────────────────────────────────────────────────────────────

  /** Load the model (idempotent — safe to call multiple times). */
  async load() {
    if (this._loaded)  return;
    if (this._loading) return this._loading;
    this._loading = this._doLoad();
    return this._loading;
  }

  async _doLoad() {
    const tf = await _importTF();

    // ── Try to load classes.json first (may have been reordered after training)
    try {
      const res = await fetch(CLASSES_URL);
      if (res.ok) {
        const json = await res.json();
        if (Array.isArray(json.classes) && json.classes.length === 13) {
          this._classes = json.classes;
        }
      }
    } catch { /* no classes.json → use defaults */ }

    // ── Load model weights ─────────────────────────────────────────────────
    try {
      this._model = await tf.loadLayersModel(MODEL_URL);
      console.log('[CNN] ✅ Loaded measurement CNN from', MODEL_URL);
    } catch (e) {
      console.warn('[CNN] Custom model not found — building untrained fallback:', e.message);
      console.warn('[CNN]   Run  python train_measurement_model.py  to generate the model.');
      this._model = _buildUntrained(tf);
    }

    // ── Warm-up: JIT-compile the graph ────────────────────────────────────
    for (let i = 0; i < WARMUP_RUNS; i++) {
      const dummy  = tf.zeros([1, IMG_SIZE, IMG_SIZE, 1]);
      const result = this._model.predict(dummy);
      result.dispose();
      dummy.dispose();
    }

    this._loaded  = true;
    this._loading = null;
    console.log(`[CNN] Warm-up done.  Classes: ${this._classes.join(' ')}`);
  }

  // ── Inference ─────────────────────────────────────────────────────────────

  /**
   * Predict the character shown in a canvas element.
   *
   * @param  {HTMLCanvasElement} canvas  – any size; normalised internally
   * @returns {Promise<{char:string, confidence:number, all:Float32Array}>}
   */
  async predict(canvas) {
    if (!this._loaded) await this.load();
    const tf = await _importTF();

    // Preprocess: canvas → [1, 28, 28, 1] float32, ink=1 / bg=0
    const tensor = tf.tidy(() => {
      const rgb  = tf.browser.fromPixels(canvas, 1);               // [H,W,1] uint8
      const f32  = tf.cast(rgb, 'float32').div(255.0);              // [H,W,1] 0-1
      const inv  = tf.scalar(1.0).sub(f32);                         // invert: ink=1
      const res  = tf.image.resizeBilinear(inv,
                     [IMG_SIZE, IMG_SIZE], true);                   // [28,28,1]
      return res.expandDims(0);                                     // [1,28,28,1]
    });

    const probs  = this._model.predict(tensor);
    const data   = await probs.data();   // Float32Array length 13
    tensor.dispose();
    probs.dispose();

    // Argmax
    let bestIdx = 0;
    for (let i = 1; i < data.length; i++) {
      if (data[i] > data[bestIdx]) bestIdx = i;
    }

    return {
      char       : this._classes[bestIdx],
      confidence : data[bestIdx],
      all        : data,
    };
  }

  /**
   * Predict from a pre-rendered pixel array (Uint8ClampedArray RGBA, row-major).
   * Useful when you already have ImageData without a full canvas.
   */
  async predictFromPixels(rgbaData, width, height) {
    const canvas = document.createElement('canvas');
    canvas.width  = width;
    canvas.height = height;
    canvas.getContext('2d').putImageData(
      new ImageData(rgbaData, width, height), 0, 0
    );
    return this.predict(canvas);
  }

  // ── Debug helper ───────────────────────────────────────────────────────────

  /** Return top-K predictions as [{ char, confidence }]. */
  topK(all, k = 3) {
    return Array.from(all)
      .map((p, i) => ({ char: this._classes[i], confidence: p }))
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, k);
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// Singleton TF.js reference (loaded once, reused).
// TF.js ^4.x is a named-export ESM module — it has no `.default` export.
// The namespace object IS the tf API (tf.tensor, tf.browser, etc.).
// Pattern: grab .default if it exists (CJS interop shim), else use namespace.
let _tf = null;
async function _importTF() {
  if (!_tf) {
    const mod = await import('@tensorflow/tfjs');
    _tf = mod.default || mod;   // .default = CJS shim; mod = pure ESM namespace
  }
  return _tf;
}

/**
 * Build an untrained model with the SAME architecture as the Python
 * training script.  Weights are random, so predictions are garbage —
 * but the geometry detector still handles all symbols and simple digits,
 * so the app remains functional until the user trains the model.
 */
function _buildUntrained(tf) {
  const model = tf.sequential({ name: 'measurement_cnn_untrained' });

  model.add(tf.layers.conv2d({
    inputShape: [IMG_SIZE, IMG_SIZE, 1],
    filters: 32, kernelSize: 3, padding: 'same', activation: 'relu',
  }));
  model.add(tf.layers.batchNormalization());
  model.add(tf.layers.maxPooling2d({ poolSize: 2 }));
  model.add(tf.layers.dropout({ rate: 0.20 }));

  model.add(tf.layers.conv2d({
    filters: 64, kernelSize: 3, padding: 'same', activation: 'relu',
  }));
  model.add(tf.layers.batchNormalization());
  model.add(tf.layers.maxPooling2d({ poolSize: 2 }));
  model.add(tf.layers.dropout({ rate: 0.25 }));

  model.add(tf.layers.flatten());
  model.add(tf.layers.dense({ units: 128, activation: 'relu' }));
  model.add(tf.layers.dropout({ rate: 0.35 }));
  model.add(tf.layers.dense({ units: 13, activation: 'softmax' }));

  model.compile({
    optimizer : 'adam',
    loss      : 'sparseCategoricalCrossentropy',
    metrics   : ['accuracy'],
  });
  return model;
}
